apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-ssd-pv-claim
  namespace: home-assistant
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
