apiVersion: v1
kind: PersistentVolume
metadata:
  name: ha-ssd-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/shared/home"
