version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/pi/.homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
#     environment:
#         - DISABLE_JEMALLOC: true
    restart: always
    ports:
      - "8123:8123"
    labels:
      kompose.service.type: LoadBalancer
    privileged: true
    network_mode: host